version: '3.8'

services:
  api:
    image: api
    container_name: api
    ports:
      - "7777:7777"
    links:
      - device
      - redis

  device:
    image: device
    container_name: device
    ports:
      - "8000:8000"
    links:
      - db
      - redis
      - mosquitto

  db:
    image: postgres
    container_name: db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=0.0.0.0
      - REDIS_PORT=6379

  mosquitto:
    container_name: mosquitto
    build:
      context: apps/mosquitto
    ports:
      - "1883:1883"
      - "8883:8883"
