version: '3.8'

services:
  db:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_URL=0.0.0.0

