import {
  API_GATEWAY_ENV,
  DATABASE_ENV,
  DEVICE_MS_ENV,
  REDIS_ENV,
} from './enum';

export abstract class ISecretService {
  API_GATEWAY_URL: API_GATEWAY_ENV | string;
  API_GATEWAY_PORT: API_GATEWAY_ENV | number;

  DEVICE_MS_URL: DEVICE_MS_ENV | string;
  DEVICE_MS_PORT: DEVICE_MS_ENV | number;

  DATABASE_TYPE: DATABASE_ENV | string;
  DATABASE_HOST: DATABASE_ENV | string;
  DATABASE_NAME: DATABASE_ENV | string;
  DATABASE_USER: DATABASE_ENV | string;
  DATABASE_PASSWORD: DATABASE_ENV | string;
  DATABASE_PORT: DATABASE_ENV | number;

  REDIS_URL: REDIS_ENV | string;
  REDIS_HOST: REDIS_ENV | string;
  REDIS_PORT: REDIS_ENV | number;
}
