export enum API_GATEWAY_ENV {
  URL = 'API_GATEWAY_URL',
  PORT = 'API_GATEWAY_PORT',
}

export enum DEVICE_MS_ENV {
  URL = 'DEVICE_MS_URL',
  PORT = 'DEVICE_MS_PORT',
}

export enum JWT_ENV {}

export enum DATABASE_ENV {
  /** Todo: Refactor db type */
  DATABASE_TYPE = 'DATABASE_TYPE',
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_NAME = 'DATABASE_NAME',
  DATABASE_USER = 'DATABASE_USER',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_PORT = 'DATABASE_PORT',
}

export enum REDIS_ENV {
  REDIS_URL = 'REDIS_URL',
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
}
